name: flame_lottie_example
description: An example for flame_lottie
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: '>=2.18.1 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flame: ^1.4.0
  flame_lottie:
    path: "../"
  flutter:
    sdk: flutter

dev_dependencies:
  flame_lint: ^0.1.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/